# MySQL Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/rag_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Upload Configuration
# Upload Configuration

rag.upload.storage-location=uploads

rag.upload.max-file-size=100MB

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


rag.upload.allowed-extensions[0]=pdf
rag.upload.allowed-extensions[1]=docx
rag.upload.allowed-extensions[2]=txt
rag.upload.allowed-extensions[3]=xlsx
rag.upload.allowed-extensions[4]=pptx

rag.upload.allowed-content-types[0]=application/pdf
rag.upload.allowed-content-types[1]=application/vnd.openxmlformats-officedocument.wordprocessingml.document
rag.upload.allowed-content-types[2]=text/plain
rag.upload.allowed-content-types[3]=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
rag.upload.allowed-content-types[4]=application/vnd.openxmlformats-officedocument.presentationml.presentation

##############################################
# OCR Configuration
##############################################

rag.ocr.enabled=true
rag.ocr.language=eng
rag.ocr.data-path=C:/Program Files/Tesseract-OCR/tessdata